image:
    file: .gitpod.dockerfile
ports:
    - port: 3000
      onOpen: ignore
    - port: 3306
      onOpen: ignore
tasks:
    - name: git terminal
      command: |
        gp await-port 3000
        git status
    - name: mysql
      command:
        mysql
      openMode: tab-after
    - name: dev server
      init: >
        cp .env.example .env;
        pipenv install;
        mysql -u root -e "CREATE DATABASE app_name";
        pipenv run init;
        pipenv run migrate;
        pipenv run upgrade;
      command: >
        pipenv run start;
      openMode: tab-after
