dist: xenial
language: python
python:
  - "3.9.0"

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.28.0

before_install:
  - chmod +x ./test.sh
  - cat .env.example > .env

install:
  - docker-compose up -d

script:
  - ./test.sh
