version: "3.3"
services:
  app_db:
    image: postgres:13
    container_name: app-db
    restart: always
    env_file: ./.env
    volumes:
      - dbdata:/var/lib/app-db/data
    ports:
      - 5432:5432
  web:
    depends_on:
      - app_db
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: app-api
    environment:
      - CHOKIDAR_USEPOLLING="true"
      - PYTHONUNBUFFERED=1
    env_file: ./.env
    volumes:
      - ./:/app
    ports:
      - 5000:5000
    working_dir: /app
    entrypoint: ["/bin/sh", "./wait_for_db.sh"]

volumes:
  dbdata:
