"""empty message

Revision ID: 01df327205f6
Revises: 
Create Date: 2020-08-04 23:53:14.201767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01df327205f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basic_support_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nametag', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='ticketstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_table('mock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('parts', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mock')
    op.drop_table('basic_support_ticket')
    # ### end Alembic commands ###
